autoDetectedPackages:
- work.slhaf
enableAutoDetect: true
entryDisplayConfig: null
funcDisplayConfig: null
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
maxColSize: null
maxNumFirst: null
maxNumFirstImportant: null
maxNumHash: null
maxNumHashImportant: null
maxObjectDepth: null
maxStrSize: null
name: xcodemap-filter
recordMode: null
sourceDisplayConfig: null
startOnDebug: null
