FROM --platform=linux/arm64 ghcr.io/graalvm/native-image-community:21

RUN microdnf install -y \
    maven \
    findutils \
    gzip \
    tar \
    which \
    file \
    && microdnf clean all

WORKDIR /workspace
